---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
          app: nginx-app
spec:
    replicas: 2
    template:
      metadata:
          labels:
              app: nginx-app
      spec:
        containers:
          - name: nginx-app
            image: nginx
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 80
    selector:
      matchLabels:
              app: nginx-app
